version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: "mongodb://db:27017/test"
      ENV: "development"
      PORT: 3000
    depends_on:
      - db
    volumes:
      - ./index.js:/usr/src/index.js
  db:
    image: mongo
networks:
  default:
    external: true
    name: local
